### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Shelly7w7** [ItzDerock/discord-html-transcripts#54] opened 2022-07-29 20:21 UTC
Currently couple of vital things are missing and I would love to see these being implemented!

- Quotes and Block Quotes
- Rendering of custom emojis in embed titles

**Comment by ItzDerock** [comment] 2022-08-06 15:03
> Quotes and Block Quotes
duplicate of #39 

> Rendering of custom emojis in embed titles
this should be doable -- will implement when I get the time.

**Comment by ItzDerock** [comment] 2022-09-20 00:53
will be implemented in [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3)

**Comment by ItzDerock** [comment] 2022-09-25 14:27
released!

**Closed by ItzDerock** 2022-09-25 14:27 UTC
Labels: enhancement, fix/in-progress
