### ISSUE TITLE
Not all messages are recovered

### ISSUE THREAD

**Issue by Sunkwii** [ItzDerock/discord-html-transcripts#35] opened 2022-06-04 15:07 UTC
I just used the module for the first time and when I open the file, only 24 messages are displayed on a total of 1184.

This problem appears only with version 2.5.6 of the module.
Older versions like 2.5.5 work fine.

discord.js: v13.7.0

**Comment by ItzDerock** [comment] 2022-06-04 15:13
Can you provide any options you are passing to the function?

**Comment by ItzDerock** [comment] 2022-06-04 15:20
Unable to reproduce, exported ~3k messages fine with `returnType: 'buffer'` as the only option.

**Comment by ItzDerock** [comment] 2022-06-04 15:26
exported ~19k messages and still works fine

**Comment by Sunkwii** [comment] 2022-06-04 16:16
```js
  const channel = discord.channels.cache.get('963640501028929556');

  const attachment = await discordTranscripts.createTranscript(channel, {
    limit: -1,
    returnType: 'attachment',
    fileName: 'transcript.html',
    minify: false,
    saveImages: false,
    useCDN: true
  });

channel.send({
      files: [attachment]
    });
```

**Comment by Sunkwii** [comment] 2022-06-04 16:17
I tried with your options, I only get `file.jpg` which is a simple white image

**Comment by ItzDerock** [comment] 2022-06-04 20:15
> I tried with your options, I only get `file.jpg` which is a simple white image

That's because I set `returnType` to buffer. 
I set it to that so I could save it as a file directly instead of sending to discord. 
this shouldn't affect the transcript though

**Comment by ItzDerock** [comment] 2022-06-04 20:15
and I think I just found the issue, pushing a fix soon

**Comment by Sunkwii** [comment] 2022-06-04 20:24
Ok, thank you very much

**Comment by ItzDerock** [comment] 2022-06-04 20:25
released as version `2.5.7`

**Closed** 2022-06-04 20:25 UTC
Labels: bug
